// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG_Z6iZE0J0sq0J4cZjngV08eFNzLC1cY',
    appId: '1:229261543898:web:1ad14f253772c3cf5618e3',
    messagingSenderId: '229261543898',
    projectId: 'fir-demo-600d7',
    authDomain: 'fir-demo-600d7.firebaseapp.com',
    storageBucket: 'fir-demo-600d7.appspot.com',
    measurementId: 'G-7Q029QTZ1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlhdkcXDSo1u6Y2D32qMTHCt120mqiUY8',
    appId: '1:229261543898:android:11661055270f892c5618e3',
    messagingSenderId: '229261543898',
    projectId: 'fir-demo-600d7',
    storageBucket: 'fir-demo-600d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLlJSd2cM6F79zsFmxO91WaBQ2DA2iVF8',
    appId: '1:229261543898:ios:18d977b9913df4735618e3',
    messagingSenderId: '229261543898',
    projectId: 'fir-demo-600d7',
    storageBucket: 'fir-demo-600d7.appspot.com',
    iosBundleId: 'com.example.todolamiya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLlJSd2cM6F79zsFmxO91WaBQ2DA2iVF8',
    appId: '1:229261543898:ios:18d977b9913df4735618e3',
    messagingSenderId: '229261543898',
    projectId: 'fir-demo-600d7',
    storageBucket: 'fir-demo-600d7.appspot.com',
    iosBundleId: 'com.example.todolamiya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG_Z6iZE0J0sq0J4cZjngV08eFNzLC1cY',
    appId: '1:229261543898:web:f6bc6703969861f05618e3',
    messagingSenderId: '229261543898',
    projectId: 'fir-demo-600d7',
    authDomain: 'fir-demo-600d7.firebaseapp.com',
    storageBucket: 'fir-demo-600d7.appspot.com',
    measurementId: 'G-G257FSMSD0',
  );
}
