// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA74rks7p0yL_l2FGimLhBuycAMxQklgK4',
    appId: '1:532609359373:web:631e53653046414f703f44',
    messagingSenderId: '532609359373',
    projectId: 'projects-161bc',
    authDomain: 'projects-161bc.firebaseapp.com',
    storageBucket: 'projects-161bc.firebasestorage.app',
    measurementId: 'G-23Q97SDHB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI7yTb0byagRep1yUNbV4HC4Bjd2xPF5s',
    appId: '1:532609359373:android:49dc71fc88fc00bc703f44',
    messagingSenderId: '532609359373',
    projectId: 'projects-161bc',
    storageBucket: 'projects-161bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDioLckc3_TXSrJYXhXMi1PKBstctWf0A',
    appId: '1:532609359373:ios:318c12ca4563a5b2703f44',
    messagingSenderId: '532609359373',
    projectId: 'projects-161bc',
    storageBucket: 'projects-161bc.firebasestorage.app',
    iosBundleId: 'com.example.ntlwallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDioLckc3_TXSrJYXhXMi1PKBstctWf0A',
    appId: '1:532609359373:ios:318c12ca4563a5b2703f44',
    messagingSenderId: '532609359373',
    projectId: 'projects-161bc',
    storageBucket: 'projects-161bc.firebasestorage.app',
    iosBundleId: 'com.example.ntlwallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgaZlsWs75VRsbW2pGNYMqEH77bs0kMBs',
    appId: '1:532609359373:web:b7547a128df7a760703f44',
    messagingSenderId: '532609359373',
    projectId: 'projects-161bc',
    authDomain: 'projects-161bc.firebaseapp.com',
    storageBucket: 'projects-161bc.firebasestorage.app',
    measurementId: 'G-VE266PKQL2',
  );

}